language:
  - cpp

dist:
  - xenial

compiler:
  - gcc

before_install:
  - sudo apt-get update
  - sudo apt-get install -y libsdl2-dev

script:
  - clang-tidy `find . -type f -name "*.cpp"` -- -Iinclude/ -Isdl/libGraph/
